### ISSUE TITLE
`Matches` with regex for numbers not working 

### ISSUE THREAD

**Issue by Muntasir2001** [bavix/gripmock#362]
Hi,

I have been trying to use [matches](https://gripmock.org/guide/matcher/input.html#input-matches) and it seems like it can't read numbers at the moment. I have tried your example in a separate file and it works. When I use numbers, it breaks.

Below is an example of the stub that I was using. I have tried without forward slashes too.

```json
{
"service": "DB",
		"method": "Update",
		"input": {
			"matches": {
				"source": "/[0-9]/",
				"ttl": "/[0-9]/"
			}
		},
		"output": {
			"data": {
				"source_info": {
					"source": 0,
					"ttl": 0,
					"status": "ACTIVE",
				}
			}
		}
}

```

Could you please have a look and assist?

**Comment by rez1dent3** [comment]
Hello. That's correct, matches only work on strings.

I didn't have a task to make it work with runes, bytes and numbers. Perhaps in the future I will consider this option.

**Comment by rez1dent3** [comment]
@Muntasir2001 I added support for numbers in matches, but It's only availability in version 3.x because it has a new match engine [stuber](https://github.com/gripmock/stuber).

You can use it like this:
```sh
docker pull bavix/gripmock:3.x-dev
```

I try not to break the 3.x-dev branch and throw the most stable code there, but version 3.x is still in development and something may change before the release.

**Comment by Muntasir2001** [comment]
@rez1dent3 thank you very much for adding it. I will try it out today and let you know how it goes!

**Comment by Muntasir2001** [comment]
I just tested it. Its not working.

This is what it shows on Postman.

<img width="1505" alt="Screenshot 2024-07-31 at 18 07 13" src="https://github.com/user-attachments/assets/03fecadf-e24c-459a-a527-4be05b184843">

Logs:
`gripmock-1  | 2024-07-31T17:07:08Z INF bytes=27 code=404 elapsed=0.359542 ip=127.0.0.1 method=POST ua=Go-http-client/1.1 url=/api/stubs/search`

Proto file:
```proto
syntax = "proto3";
option go_package = "github.com/bavix/gripmock/protogen/example/simple";

package simple;

service Gripmock {
  rpc SayHello (Request) returns (Reply);

  rpc SayBye (NewRequest) returns (Reply);
}

message Request {
  string name = 1;
}

message NewRequest {
  uint32 year = 1;
}

message Reply {
  string message = 1;
  int32 return_code = 2;
}
```

Stub file
```json
[
	{
		"service": "Gripmock",
		"method": "SayHello",
		"input": {
			"matches": {
				"name": "^grip.*$"
			}
		},
		"output": {
			"data": {
				"message": "Hello GripMock"
			}
		}
	},
	{
		"service": "Gripmock",
		"method": "SayBye",
		"input": {
			"matches": {
				"year": "/[0-9]/"
			}
		},
		"output": {
			"data": {
				"message": "Hello GripMock"
			}
		}
	}
]
```

**Comment by rez1dent3** [comment]
replace
```
				"year": "/[0-9]/"
```

to
```
				"year": "[0-9]"
```

If it doesn't work, then I'll start watching carefully.

**Comment by Muntasir2001** [comment]
Tried it just now.

Still no luck

**Comment by rez1dent3** [comment]
Ok.. I will test your case separately in the near future.

**Comment by Muntasir2001** [comment]
Out of curiosity, could you please share your stub and proto file which you have used to test the new match engine?

**Comment by rez1dent3** [comment]
Filtering is covered by unit tests:
- https://github.com/gripmock/deeply/blob/master/contains_test.go
- https://github.com/gripmock/deeply/blob/master/equals_test.go
- https://github.com/gripmock/deeply/blob/master/matches_test.go
- https://github.com/gripmock/deeply/blob/master/ranker_test.go

The filtering engine is also covered with unit tests:
- https://github.com/gripmock/stuber/blob/master/stuber_test.go
- https://github.com/gripmock/stuber/blob/master/storage_test.go
- https://github.com/gripmock/stuber/blob/master/query_test.go

There are also integration tests already inside gripmock:
- https://github.com/bavix/gripmock/tree/master/example

As part of the testing, I will write integration tests and fix the code so that it doesn't break in the future.

**Comment by rez1dent3** [comment]
The bug was in ranker, not in matches. Ranker returned 0 and stuber marked the stub as not found and did not give it to gripmock.

You wanted to see the stab:
https://github.com/bavix/gripmock/blob/3e4d95e7f2e566b5cbdb49b4c2cc222cd8ec82b5/example/simple/stub/uint64_int64.yml#L17-L24

Don't forget to get the latest image:
```sh
docker pull bavix/gripmock:3.x-dev
```
